services:
  postgres:
    image: postgres:12-alpine
    container_name: clients_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      PGDATA: ${PGDATA_PATH}
    env_file:
      .env
    restart: on-failure