server:
  port: 9595

spring:
  application:
    name: UnibellTrialTask
  docker:
    compose:
      enabled: true
      file: docker-compose.yml
      stop:
        command: stop
        timeout: 10
  data:
    rest:
      base-path: /api
  datasource:
    url: jdbc:postgresql://localhost/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}