server:
  port: 9595

spring:
  application:
    name: UnibellTrialTask
  docker:
    compose:
      enabled: true
      file: docker-compose.yml
      stop:
        command: stop
        timeout: 10
  data:
    rest:
      base-path: /api
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

logging:
  level:
    root: WARN
    com.example.trial_task: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG